language: java
before_install:
    ant --help
install:
    ant -f continuousintegration.xml -lib ./lib
script:
    ant -f continuousintegration.xml test
after_script:
    cat TEST-com.main.PointTest.txt
